### ISSUE TITLE
[HLMV] Cross Platform Support?

### ISSUE THREAD

**Issue by Xylemon** [SamVanheer/HalfLifeAssetManager#10]
I was made aware of your model viewer and it peaked my interest. I am currently looking into trying to get the current Windows binary working under Wine, however it seems the toolkit, render, and other libs used are all cross platform. Is there plans to create a MakeFile for other platforms such as Linux?

**Comment by SamVanheer** [comment]
Eventually, yes. I might use CMake to generate the project files in the future, which would make generating Makefiles somewhat easy.

**Comment by SamVanheer** [comment]
Copying my comments from the duplicate issue:

---

See Shepard's work for things that need doing: https://github.com/Solokiller/HL_Tools/compare/dev...JoelTroch:feature/linux

> Would be highly appreciated! Tell me if there is a way to help.
> Any Windows-dependent libraries currently used?

Nothing exclusive to Windows, but one of the libraries (GLEW) will be removed once i've upgraded everything to use shaders since Qt's OpenGL APIs provide what's needed.

The rest will need to be updated to work on Linux since i've only made Windows builds for Ogg, Vorbis and VorbisFile. I haven't looked into what that's going to take, but i don't expect it will be too complicated.

I'd want to look into getting those libraries from a package manager like vcpkg or Conan if possible.

---

Note: i've already removed GLEW and replaced Ogg Vorbis and VorbisFile with libnyquist. The project already uses vcpkg. I tested a Linux build yesterday, there is some work required to get it to compile but i don't think it's that much.

Once i've completed feature work for 2.0.0 i'll fix the compile errors and test the Linux build to see if anything else needs doing.

**Comment by SamVanheer** [comment]
Here's the development build running on Ubuntu 20.04:
![](https://media.discordapp.net/attachments/484363370640703509/1058874895901134858/image.png)

It's experimental but it works. It looks like settings don't save so it needs more work but this is good progress.

**Comment by SamVanheer** [comment]
I've fixed the settings issue, the case sensitivity for the recent files list was off. Looks like the Linux version is working pretty well, but i haven't tested every feature.

**Comment by DeafMan1983** [comment]
And I have problem with spdlog under Ubuntu 22.04.1 Where do I find current version or latest version of spdlog and how do I force 32 Bit version on 64 Bit linux.

**Comment by SamVanheer** [comment]
I fixed the Linux version having transparency issues in some cases (e.g. running in a virtual machine) so it looks to be pretty stable now. I have a few more things to finish up, then i can release a beta build for testing.

**Comment by SamVanheer** [comment]
I've released Version 3 beta 1. You can try out the Linux version by downloading the Debian package in the Releases page: https://github.com/SamVanheer/HalfLifeAssetManager/releases/tag/HLAM-V3.0.0-beta001

**Comment by MesaBlack** [comment]
Linux beta: Can't load bsp's. Can't load 7z's or zip's of mods. (hope it's the right place)

**Comment by SamVanheer** [comment]
It's not supposed to do any of that. Read the [manual](https://github.com/SamVanheer/HalfLifeAssetManager/blob/master/docs/manual/HalfLifeAssetManagerManual.md) first so you know what the program is meant to do.

**Comment by MesaBlack** [comment]
thx

**Comment by SamVanheer** [comment]
No problems have been reported with the Linux version so i'm considering this as completed.
