### ISSUE TITLE
Error Coudn't create OpenGL context

### ISSUE THREAD

**Issue by davbrasan** [SamVanheer/HalfLifeAssetManager#148]
I do not have a video card, has how to use directX?

**Comment by Solokiller** [comment]
This tool only supports OpenGL.

**Comment by DavidBrazSan** [comment]
OK. thanks for answering

**Comment by Solokiller** [comment]
Note: this error was caused by Qt trying to use a different OpenGL implementation that does not support the version of OpenGL used by this program. The latest beta fixes this bug. You can try it or wait for V1.3.0 (should be this weekend) to be released to see if it works on your system.

**Comment by DavidBrazSan** [comment]
The application runs, it's an error because my OpenGL is 1.1, but when I try to load a file, it doesn't load.

**Comment by Solokiller** [comment]
Are you opening a Half-Life 1 model file? Are there any errors?

**Comment by DavidBrazSan** [comment]
Not. My OpenGl is 1.1. When starting the app it warns that my OpenGl is old, I press OK and it opens the interface but when I try to load a v_usp.mdl file the app freezes and closes.

**Comment by Solokiller** [comment]
What are your system specifications? What version of Windows do you have, which graphics card do you have? Are your drivers up to date?

**Comment by DavidBrazSan** [comment]
Chipset Intel® G41 Express

**Comment by Solokiller** [comment]
According to [Intel's documentation](https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/g41-chipset-brief.pdf) your card supports OpenGL 2.0, so this should be working. I'll take a look around, see if maybe i'm accidentally using something newer without checking if it's available, otherwise i'll see if i can get you to provide a more detailed crash report somehow.

The documentation does say that only Windows XP is supported, though i'm finding posts from users that have Windows 8.1. What operating system are you on?

Can you also turn on log output and show what the program writes to it? This page explains how to do that: https://github.com/Solokiller/HL_Tools/wiki/Half-Life-Asset-Manager-Configuring-Log-File-Output

**Comment by DavidBrazSan** [comment]
Windows 10

**Comment by Solokiller** [comment]
I found only one API call that could cause crashes, it'll be replaced in HLAM 2.0. I don't think it's being called though.

Can you try a couple different models to see if it always crashes or only with specific models? If it's a custom model, can you also provide a download link?

Can you also provide the log output so i can see if there's anything problematic being logged?

**Comment by DavidBrazSan** [comment]
Log:

Debug: QWindowsIntegration::createPlatformOpenGLContext QSurfaceFormat(version 1.0, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 4, greenBufferSize 4, blueBufferSize 4, alphaBufferSize 0, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile) (:0, )
Debug: QWindowsGLContext::QWindowsGLContext 0x150adb8 GDI  requested:  QSurfaceFormat(version 1.0, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 4, greenBufferSize 4, blueBufferSize 4, alphaBufferSize 0, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile) 
    obtained # 7 GDI QSurfaceFormat(version 1.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 32, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
     PIXELFORMATDESCRIPTOR dwFlags=0x8465 PFD_DRAW_TO_WINDOW PFD_SUPPORT_OPENGL PFD_SUPPORT_COMPOSITION PFD_GENERIC_FORMAT PFD_DOUBLEBUFFER iPixelType=0 cColorBits=32 cRedBits=8 cRedShift=16 cGreenBits=8 cGreenShift=8 cBlueBits=8 cBlueShift=0 cDepthBits=32 cStencilBits=8 iLayerType=0 cAlphaBits=8 cAlphaShift=0 cAccumBits=64 cAccumRedBits=16 cAccumGreenBits=16 cAccumBlueBits=16 cAccumAlphaBits=16  swap interval:  -1 
    default:  ContextFormat: v1.1 profile: QSurfaceFormat::NoProfile options: QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions) 
    HGLRC= 0x10001 (:0, )

Screenshot:
![bandicam 2021-08-16 11-22-02-643](https://user-images.githubusercontent.com/60136669/129580494-f7f40fa7-2d09-45ce-a4ee-3ca38af8f358.jpg)
![bandicam 2021-08-16 11-23-13-298](https://user-images.githubusercontent.com/60136669/129580503-1091cb65-a34a-4f99-bf07-642db6f5dd34.jpg)

**Comment by Solokiller** [comment]
I've made a new beta with more log output: https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.3.0-beta008

I don't think i can fix this problem right now. Your driver doesn't support OpenGL well enough, so what i'm going to do is implement shaders with HLAM 2.0.0 and then try get to ANGLE working so you can use that instead. ANGLE implements part of the OpenGL API by using DirectX under the hood which your GPU does support well enough. Hopefully everything will work properly then.

It'll be a few weeks at minimum before i can produce a test build so i'll let you know when it's ready.

**Comment by DavidBrazSan** [comment]
when I try to load the app closes

**Comment by Solokiller** [comment]
Is there anything in the log file?

**Comment by SamVanheer** [comment]
I've investigated this further: ANGLE doesn't support the use of deprecated OpenGL functions so it won't be possible to rely on the ANGLE renderer to solve this problem right now.

HLAM 2.0.0 won't upgrade the graphics code to use shaders so it probably won't work for you. I'm planning to do that upgrade in 3.0.0 but i don't know if it'll work any better.

Your graphics card only supports DirectX 10 whereas the shader upgrade will be using the equivalent of DirectX 11 so i doubt this'll work for you.

Since this is an integrated card it may be better to get a dedicated GPU. Even a cheap one should support OpenGL 3.3+ and DirectX 11+. Even if it doesn't support those it should have full support for deprecated desktop OpenGL functions. The lack of support from the integrated card is why the current version fails to work so any dedicated GPU you can get should allow you to run the current version.

**Comment by SamVanheer** [comment]
HLAM won't work at all once it's been upgraded to use newer OpenGL functionality, so it will not be possible to make it work with your integrated graphics card. I'd recommend acquiring a dedicated graphics card that supports OpenGL 3.3 or newer.
