### ISSUE TITLE
Transparent things in transparent screenshots are not transparent

### ISSUE THREAD

**Issue by Droooga** [SamVanheer/HalfLifeAssetManager#274]
I think this one is pretty self-explanatory

![kuva](https://user-images.githubusercontent.com/85588460/223183075-dd0e1766-17af-493d-bd28-0ed121fe38ea.png)

![kuva](https://user-images.githubusercontent.com/85588460/223183945-c3a96fc3-c6fc-42d5-aae5-c6b4a886c51a.png)

this one is in additive rendermode

![kuva](https://user-images.githubusercontent.com/85588460/223184367-a0666ca2-4a45-4b3e-98d8-b7e867905413.png)

**Comment by SamVanheer** [comment]
This happens because screenshots are a copy of the currently rendered scene, so the background color is mixed in with transparent objects.

A future update will introduce the use of modern OpenGL shaders that allow screenshots to be made using a separate scene render that can exclude the background color. The manual explains how to work around this issue for now.

**Comment by SamVanheer** [comment]
I've mostly fixed this. Transparency works in all cases except additive because additive doesn't actually have a transparent alpha channel. The background color is mixed in when additive meshes are drawn but the alpha value is 1, so the resulting alpha value in the transparent image is also 1.

I could change it to max out the alpha value at something like 0.9 to force transparency for additive meshes but that could cause other problems.

Note that transparent screenshots now require OpenGL framebuffers (added to core in 3.0, available as an extension for older OpenGL versions), so your driver must provide that feature for this to be enabled.
