### ISSUE TITLE
Linux builds artifacts?

### ISSUE THREAD

**Issue by Nord1cWarr1or** [SamVanheer/HalfLifeAssetManager#280]
Hi. Why did you disable Artifacts for Linux? I need this, but I can't figure out how to compile.

**Comment by SamVanheer** [comment]
Because the Linux version isn't ready yet. I've gotten the Linux version to the point where it will run in my Ubuntu virtual machine but it's not ready for distribution yet. The artifact version won't run because the third party dependencies need to be bundled in and required dependencies that need installing with a package manager need to be made note of as well.

I've got a couple other projects that need finishing first before i can focus my attention on getting this done. It's too soon to say when that'll be but when it's ready i'll close this issue as completed.

**Comment by Nord1cWarr1or** [comment]
Ok, ty

**Comment by SamVanheer** [comment]
I've fixed a couple Linux-specific issues and set up the CI workflow to produce artifacts. You should now be able to run those builds if you install these dependencies:
* libopenal1
* qtbase5-dev

Also make sure to install an appropriate OpenGL driver.

Note that the Linux version is experimental for version 2. There is a problem that causes transparent rendering to show what's behind the program window and this can't be fixed until the renderer is overhauled, which is planned for version 3.

**Comment by MesaBlack** [comment]
> where it will run in my Ubuntu virtual machine

Will there be a .deb Linux Debian version? I have ChromeOS, and there's a Linux dev environment.

**Comment by SamVanheer** [comment]
I haven't looked into packaging yet but i'll keep that in mind.
