### ISSUE TITLE
Xash support

### ISSUE THREAD

**Issue by Nord1cWarr1or** [SamVanheer/HalfLifeAssetManager#281]
Why did you disable support for models compiled by the Xash compiler? They are fully compatible with GoldSrc.

**Comment by Nord1cWarr1or** [comment]
Although no, I misspoke. I'm talking about models for CS/HL, but compiled using the Xash compiler.

**Comment by SamVanheer** [comment]
Asset Manager strictly follows the Studiomodel version 10 specification. Xash models re-purpose unused data in the specification for other things which caused the program to crash when some Xash models were loaded. Since saving a Xash model also strips anything that's not part of the specification i decided to instead have the model forwarded to Xash model viewer.

I can change it so that Xash models can load and the unused data is ignored instead of being loaded correctly but then there's a need to warn users if they're about to save a Xash model since it'll lose that extra data.

Adding support for Xash models directly isn't an option because the point of this program is to view and edit Half-Life models, not flavors used by specific mods. That's what Xash's own model viewer is for.

**Comment by SamVanheer** [comment]
I've reworked Xash model support to allow Xash models to load. You can choose whether to redirect to Xash model viewer and if you save a Xash model it'll warn about potential loss of data.

You can try the changes out in the latest automated build once it has completed: https://github.com/SamVanheer/HalfLifeAssetManager/actions/runs/6440725570
