### ISSUE TITLE
(Not only) Hitbox editing issue - integer numbers

### ISSUE THREAD

**Issue by Qwertyus3D** [SamVanheer/HalfLifeAssetManager#288]
You can manually set only integer values, "." symbol can not be entered. Also, a value can not be altered or pasted from clipboard, if not integer. It's not only hitbox editing issue, other parameters (which are supposed to be not only integer) also do not support fractional numbers.

**Comment by SamVanheer** [comment]
Numeric input uses your computer's default locale which is why it's misinterpreting the use of `.` characters. I've changed it to use the `en_US` locale just like the game to make it behave consistently.

When it's done you can try the CI build to see if it's working properly: https://github.com/SamVanheer/HalfLifeAssetManager/actions/runs/8133443702

Let me know if it's working correctly or if it needs more adjustments.
